Features/improve review logging
UKHO/taskmanager pull request #650
Opened 2020-09-15 11:00 UTC by benbhall

2020-09-15 14:04 UTC, bonpoole approved these changes

2020-09-15 15:48 UTC, UKHOGreg requested changes

2020-09-15 15:48 UTC, UKHOGreg commented on src/Portal/Portal/Pages/DbAssessment/Review.cshtml.cs
> +            LogContext.PushProperty("PortalResource", nameof(OnPostTerminateAsync));
```suggestion
            LogContext.PushProperty("PortalResource", nameof(OnGet));
```

2020-09-16 08:46 UTC, UKHOGreg approved these changes

2020-09-16 08:50 UTC, merged