Features/ncne withdrawl newpage
UKHO/taskmanager pull request #654
Opened 2020-10-09 10:26 UTC by ssrajan

Following changes are done in the existing pages for New withdrawal workflow (New Withdrawal page is created)

**1.	New Withdrawal Page**
a.	Workflow type will be fixed as ‘Withdrawal’
b.	Duration will be fixed as ‘Three Weeks’
c.	Only Compiler and V1 roles will be used
d.	publication date is used as Withdrawal Date, Repromat date is not used.

**2.	New Task Page (NCNE task)**
a.	In the workflow Type list, Withdrawal should not be available for selection

**3.	Landing Page**

i)	Publication column will be renamed as ‘Publication/Withdrawal’
ii)	Form column will be renamed as ‘Forms / Withdrawal Actions ‘ 
iii)	Date for commit to Print will display ‘N/A’ for withdrawals
iv)    On Assign Users, the new user will be assigned to either Compiler/V1 as per the current stage and the stage user will be updated.
iv)	Status column will be displayed for Withdrawal workflow as follows
a.	Withdrawal Action
b.	V1
c.	V1 Rework
d.	CIS
e.	PMC Withdrawal
f.	Consider Email SDR 

**4.	Workflow page**
i)	The following will be the stages for the new workflow
a.	Withdrawal Action 
(Legend / Consequential / Misc Action)
b.	V1
c.	V1 Rework
d.	CIS
e.	PMC Withdrawal
f.	Consider Email SDR
ii)	All the status will have Complete button and depend on the previous stage ( Except V1 and V1 rework which follows the flow as in NCNE)
iii)	When ‘Consider Email SDR’ stage is completed, Complete button for completing the workflow will be enabled.
iv)	The following are the roles assigned to the Stages
a.	Withdrawal Action and V1 Rework -->  Compiler
b.	All other stages -->  V1
**5. History page**
i) All Terminated and Completed workflow task should be listed and viewable as read-only
ii) Should be able to filter and see only Withdrawal tasks.

2020-10-09 11:34 UTC, UKHOGreg commented
I think that we need some more unit test coverage for this change.

For example, `StageTypeFactory.cs` does not have any unit tests,

`WorkflowStageHelper.GetNextStagesForCompletion` has a fair amount of logic added, yet there are no new unit tests to cover this.

2020-10-09 14:08 UTC, UKHOGreg requested changes

2020-10-09 14:08 UTC, UKHOGreg commented on src/NCNEPortal/Pages/Withdrawal.cshtml.cs
> +                _logger.LogError(ex, "Error while initializing the new task page");
```suggestion
                _logger.LogError(ex, "Error while initializing the withdrawal page");
```

2020-10-09 14:08 UTC, UKHOGreg commented on src/NCNEPortal/Pages/Withdrawal.cshtml
> +    ViewData["Title"] = "New Chart / New Edition New Task";
`New Task`?

2020-10-09 14:08 UTC, UKHOGreg commented on src/NCNEPortal/Pages/Withdrawal.cshtml
> +    <!--<div id="taskInformation"></div> -->
Comment

2020-10-09 14:08 UTC, UKHOGreg commented on src/NCNEPortal/Pages/Withdrawal.cshtml
> +                                        @Html.DropDownListFor(m => m.WorkflowType, Model.WorkflowTypes, "", new { })*@
Comment

2020-10-09 14:08 UTC, UKHOGreg commented on src/NCNEPortal/Pages/Workflow.cshtml.cs
> +        //public SelectList CompilerList { get; set; }
Comment

2020-10-09 14:08 UTC, UKHOGreg commented on src/NCNEPortal/Pages/Workflow.cshtml
> +        @*@await Component.InvokeAsync("TaskInfo", new { workflow = Model })*@
Comment

2020-10-09 14:21 UTC, ssrajan commented on src/NCNEPortal/Pages/Workflow.cshtml
> +        @*@await Component.InvokeAsync("TaskInfo", new { workflow = Model })*@
Removed

2020-10-09 14:21 UTC, ssrajan commented on src/NCNEPortal/Pages/Workflow.cshtml.cs
> +        //public SelectList CompilerList { get; set; }
Removed

2020-10-09 14:21 UTC, ssrajan commented on src/NCNEPortal/Pages/Withdrawal.cshtml
> +                                        @Html.DropDownListFor(m => m.WorkflowType, Model.WorkflowTypes, "", new { })*@
Removed

2020-10-09 14:22 UTC, ssrajan commented on src/NCNEPortal/Pages/Withdrawal.cshtml
> +    <!--<div id="taskInformation"></div> -->
Removed

2020-10-09 14:22 UTC, ssrajan commented on src/NCNEPortal/Pages/Withdrawal.cshtml
> +    ViewData["Title"] = "New Chart / New Edition New Task";
Changed to 'New withdrawal task'

2020-10-09 14:24 UTC, ssrajan commented on src/NCNEPortal/Pages/Withdrawal.cshtml.cs
> +                _logger.LogError(ex, "Error while initializing the new task page");
Changed as suggested

2020-10-09 14:25 UTC, ssrajan commented on src/NCNEPortal/Pages/Withdrawal.cshtml.cs
> +        private readonly ILogger<NewTaskModel> _logger;
Changed to Withdrawal model

2020-10-09 14:26 UTC, ssrajan commented on src/NCNEPortal/wwwroot/js/Workflow.js
> +    $('#DateSting *').prop('disabled', true);
Thanks. Spelling mistake corrected in Js and chtml files

2020-10-09 14:29 UTC, ssrajan commented on src/NCNEPortal/Pages/Shared/Components/WorkflowStage/Default.cshtml
> +            @if (Model.TaskStageTypeId < (int)NcneTaskStageType.Publication
This is correct. We are not displaying InProgress for Publication, since the subtasks have the status.

2020-10-09 14:48 UTC, ssrajan commented on src/NCNEPortal/Pages/Index.cshtml
> +                            {<a>N/A</a>}
Changed to span. Thanks

2020-10-09 14:54 UTC, UKHOGreg approved these changes

2020-10-12 09:10 UTC, bonpoole approved these changes

2020-10-12 09:16 UTC, merged