Features/ncne withdrawal testcases
UKHO/taskmanager pull request #665
Opened 2020-10-20 14:00 UTC by ssrajan

**New Withdrawal Task page**

Remove Duration
Make chart number mandatory
Remove New Chart/New Edition header

**Withdrawal Workflow page**

Remove Duration
Remove Commit to Print
H Forms to be renamed to match landing page column header (Forms/Withdrawal Actions)
Chart number is mandatory
Chart number is read only after V1 is Completed
Change Consider Email SDR to Consider Email to SDR

2020-10-20 14:33 UTC, UKHOGreg requested changes

2020-10-20 14:33 UTC, UKHOGreg commented on src/NCNEPortal/Pages/Withdrawal.cshtml
> +            </div>*@
Comment?

2020-10-20 14:33 UTC, UKHOGreg commented on src/NCNEPortal.TestAutomation.Framework/Pages/NewTaskPage.cs
> +    public class NewTaskPage : PageBase, ILandingPage
Forgive me, but why does `NewTaskPage` implement `ILandingPage`?

2020-10-20 14:33 UTC, UKHOGreg commented on src/NCNEPortal.TestAutomation.Framework/Pages/WithdrawalPage.cs
> +    public class WithdrawalPage : PageBase, ILandingPage
Forgive me, but why does `WithdrawalPage` implement `ILandingPage`?

2020-10-20 14:33 UTC, UKHOGreg commented on src/NCNEPortal.UnitTests/PageValidationTests.cs
> +        public void Validation_for_ValidateNewTaskPage_missing_ChartNoe_fails_for_Withdrawal(string chartNo)
```suggestion
        public void Validation_for_ValidateNewTaskPage_missing_ChartNo_fails_for_Withdrawal(string chartNo)
```

2020-10-20 15:46 UTC, ssrajan commented on src/NCNEPortal/Pages/Withdrawal.cshtml
> +            </div>*@
Removed the commented code

2020-10-20 15:47 UTC, ssrajan commented on src/NCNEPortal.UnitTests/PageValidationTests.cs
> +        public void Validation_for_ValidateNewTaskPage_missing_ChartNoe_fails_for_Withdrawal(string chartNo)
corrected the spelling mistake

2020-10-20 15:47 UTC, ssrajan commented on src/NCNEPortal.TestAutomation.Framework/Pages/NewTaskPage.cs
> +    public class NewTaskPage : PageBase, ILandingPage
Its a common interface to have Navigate method. Now renamed  to IPage

2020-10-20 15:48 UTC, ssrajan commented on src/NCNEPortal.TestAutomation.Framework/Pages/WithdrawalPage.cs
> +    public class WithdrawalPage : PageBase, ILandingPage
Its a common interface to have Navigate method. Now renamed  to IPage

2020-10-20 16:14 UTC, UKHOGreg requested changes

2020-10-20 16:14 UTC, UKHOGreg commented on src/Common.TestAutomation.Framework/Pages/ILandingPage.cs
> +    public interface IPage
Filename is now incorrect ☹

2020-10-20 16:19 UTC, ssrajan commented on src/Common.TestAutomation.Framework/Pages/ILandingPage.cs
> +    public interface IPage
Yes.  changed now

2020-10-20 16:26 UTC, UKHOGreg approved these changes

2020-10-21 08:30 UTC, bonpoole approved these changes

2020-10-21 08:38 UTC, merged